name: Synchronize Trivy to JIRA
description: Synchronizes security vulnerabilities found by Trivy with JIRA issue tracker

inputs:
  trivy-results:
    description: Path to Trivy results file in JSON format containing all found vulnerabilities
    required: true
  min-severity:
    description: Minimum severity to be processed. Can be `UNKNOWN`, `LOW`, `MEDIUM`, `HIGH` or `CRITICAL`.
    required: false
    default: HIGH
  jira-project-key:
    description: Key of JIRA project to sync issues to.
    required: true
  jira-issuetype-name:
    description: Name of JIRA issuetype to use for issues.
    required: true
  jira-cve-id-field-id:
    description: ID of JIRA custom field to receive the CVE ID. This field is used to match vulnerabilities.
    required: true

runs:
  using: node20
  main: index.js
