name: Hello JS Action
description: Demo action to show how to use a JS action

inputs:
  answer:
    description: The Answer to Life, the Universe and Everything else
    required: true

runs:
  using: node20
  main: index.js
