name: Run Trivy to JIRA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab

jobs:
  run-trivy-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our actions for later
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "python:3.4-alpine" # demo image
          format: json
          output: trivy-results.json

      - name: Save Trivy results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.json
          if-no-files-found: error
          retention-days: 7
          compression-level: 9

      - name: Synchronize Trivy result to JIRA
        uses: ./.github/actions/sync-trivy-to-jira
        with:
          trivy_results: trivy-results.json
          min_severity: ${{ vars.MIN_SEVERITY }}
          jira_project_key: ${{ vars.JIRA_PROJECT_KEY }}
          jira_issuetype_name: ${{ vars.JIRA_ISSUETYPE_NAME }}
          jira_cve_id_field_id: ${{ vars.JIRA_CVE_ID_FIELD_ID }}
          jira_cve_id_field_name: ${{ vars.JIRA_CVE_ID_FIELD_NAME }}
          jira_cve_status_field_id: ${{ vars.JIRA_CVE_STATUS_FIELD_ID }}
          jira_priority_ids: ${{ vars.JIRA_PRIORITY_IDS }}
        env:
          JIRA_DOMAIN: ${{ vars.JIRA_DOMAIN }}
          JIRA_EMAIL: ${{ vars.JIRA_EMAIL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
