name: Run Trivy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab

jobs:
  run-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "python:3.4-alpine" # demo image
          format: json
          output: trivy-results.json

      - name: Save Trivy results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.json
          if-no-files-found: error
          retention-days: 7
          compression-level: 9
